## Disney Plus Movies and TV Shows.
### Found in Kaggle(https://www.kaggle.com/datasets/unanimad/disney-plus-shows ).
Disney+ wants to know the most watched genre of movies and series of their stock to invest in the production of new series and movies, then, Disney+ want to reduce costs removing the least seen 30 movies, series and documentaries but they don’t want to remove the films that are no more than 9 years produced.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df= pd.read_csv('disney_plus_shows.csv')

In [4]:
df.head()

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,director,writer,actors,language,country,awards,metascore,imdb_rating,imdb_votes
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",Gil Junger,"Karen McCullah, Kirsten Smith","Heath Ledger, Julia Stiles, Joseph Gordon-Levi...","English, French",USA,2 wins & 13 nominations.,70.0,7.3,"283,945"
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",NaN,NaN,"Josh Brener, Michaela Dietz, Bert Davis, Abiga...",English,"UK, USA, Canada",NaN,NaN,6.2,124
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",Stephen Herek,"Dodie Smith (novel), John Hughes (screenplay)","Glenn Close, Jeff Daniels, Joely Richardson, J...","English, Spanish","USA, UK",Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785"
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical","Jim Kammerud, Brian Smith","Jim Kammerud (story), Dan Root (story), Garret...","Barry Bostwick, Jason Alexander, Martin Short,...",English,USA,5 wins & 10 nominations.,NaN,5.8,"7,434"
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",Kevin Lima,"Dodie Smith (novel), Kristen Buckley (story), ...","Glenn Close, Gérard Depardieu, Ioan Gruffudd, ...",English,"USA, UK",Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444"

In [67]:
#df[df['title']== 'Iron Man']

In [5]:
#df['language'].unique()

In [77]:
df.dtypes

imdb_id         object
title           object
plot            object
type            object
rated           object
year            object
released_at     object
added_at        object
runtime         object
genre           object
director        object
writer          object
actors          object
language        object
country         object
awards          object
metascore      float64
imdb_rating    float64
imdb_votes     float64
dtype: object

In [7]:
df['imdb_votes'] = df['imdb_votes'].str.replace(',', '.')

df['imdb_votes'] = pd.to_numeric(df['imdb_votes'], errors='coerce')

print(df)

       imdb_id                                       title  \
0    tt0147800                  10 Things I Hate About You
1    tt7019028                        101 Dalmatian Street
2    tt0115433                              101 Dalmatians
3    tt0324941  101 Dalmatians 2: Patch's London Adventure
4    tt0211181                              102 Dalmatians
..         ...                                         ...
987  tt3544734                                      Zapped
988  tt0186726             Zenon: Girl of the 21st Century
989  tt0271271                           Zenon: The Zequel
990  tt0379060                                   Zenon: Z3
991  tt2948356                                    Zootopia

                                                  plot    type  rated   year  \
0    A pretty, popular teenager can't go out on a d...   movie  PG-13   1999
1    This series follows the lives of Delilah and D...  series    NaN  2018–
2    An evil high-fashion designer plots to steal D...   movie      G   1996
3    Being one of 101 takes its toll on Patch, who ...   movie      G   2002
4    Cruella DeVil gets out of prison and goes afte...   movie      G   2000
..                                                 ...     ...    ...    ...
987  When Zoey's mom remarries, Zoey finds it hard ...   movie   TV-G   2014
988  An inquisitive teenager pries into suspected d...   movie   TV-G   1999
989  A mischievous fifteen-year-old girl living on ...   movie   TV-G   2001
990  The heroine sets out to win an important compe...   movie   TV-G   2004
991  In a city of anthropomorphic animals, a rookie...   movie     PG   2016

     released_at           added_at  runtime  \
0    31 Mar 1999  November 12, 2019   97 min
1    25 Mar 2019  February 28, 2020      NaN
2    27 Nov 1996  November 12, 2019  103 min
3    21 Jan 2003  November 12, 2019   74 min
4    22 Nov 2000  November 12, 2019  100 min
..           ...                ...      ...
987  23 Jun 2014  November 12, 2019  102 min
988  23 Jan 1999  November 12, 2019   97 min
989  12 Jan 2001  November 12, 2019  100 min
990  11 Jun 2004  November 12, 2019   81 min
991  04 Mar 2016  November 12, 2019  108 min

                                                 genre  \
0                               Comedy, Drama, Romance
1                            Animation, Comedy, Family
2                     Adventure, Comedy, Crime, Family
3        Animation, Adventure, Comedy, Family, Musical
4                            Adventure, Comedy, Family
..                                                 ...
987                            Comedy, Family, Fantasy
988                  Adventure, Comedy, Family, Sci-Fi
989                  Comedy, Family, Adventure, Sci-Fi
990                  Adventure, Comedy, Family, Sci-Fi
991  Animation, Adventure, Comedy, Crime, Family, M...

                                              director  \
0                                           Gil Junger
1                                                  NaN
2                                        Stephen Herek
3                            Jim Kammerud, Brian Smith
4                                           Kevin Lima
..                                                 ...
987                                      Peter DeLuise
988                                    Kenneth Johnson
989                                         Manny Coto
990                                         Steve Rash
991  Byron Howard, Rich Moore, Jared Bush(co-director)

                                                writer  \
0                        Karen McCullah, Kirsten Smith
1                                                  NaN
2        Dodie Smith (novel), John Hughes (screenplay)
3    Jim Kammerud (story), Dan Root (story), Garret...
4    Dodie Smith (novel), Kristen Buckley (story), ...
..                                                 ...
987  Leslie Margolis (based on the novel "Boys Are ...
988  Marilyn Sadler (book), Roger Bollen (book), St...
989  Marilyn Sadler (book), Roger Bollen (book), St...
990  Marilyn Sadler (character from the book "Zenon...
991  Byron Howard (story by), Rich Moore (story by)...

                                                actors          language  \
0    Heath Ledger, Julia Stiles, Joseph Gordon-Levi...   English, French
1    Josh Brener, Michaela Dietz, Bert Davis, Abiga...           English
2    Glenn Close, Jeff Daniels, Joely Richardson, J...  English, Spanish
3    Barry Bostwick, Jason Alexander, Martin Short,...           English
4    Glenn Close, Gérard Depardieu, Ioan Gruffudd, ...           English
..                                                 ...               ...
987  Zendaya, Chanelle Peloso, Spencer Boldman, Emi...           English
988  Kirsten Storms, Raven-Symoné, Stuart Pankin, H...           English
989  Kirsten Storms, Shadia Simmons, Lauren Maltby,...           English
990  Kirsten Storms, Lauren Maltby, Alyson Morgan, ...           English
991  Ginnifer Goodwin, Jason Bateman, Idris Elba, J...           English

              country                                             awards  \
0                 USA                           2 wins & 13 nominations.
1     UK, USA, Canada                                                NaN
2             USA, UK  Nominated for 1 Golden Globe. Another 3 wins &...
3                 USA                           5 wins & 10 nominations.
4             USA, UK  Nominated for 1 Oscar. Another 1 win & 7 nomin...
..                ...                                                ...
987       Canada, USA                             5 wins & 1 nomination.
988               USA                                     2 nominations.
989  USA, New Zealand                                      1 nomination.
990               USA                                                NaN
991               USA     Won 1 Oscar. Another 46 wins & 71 nominations.

     metascore  imdb_rating  imdb_votes
0         70.0          7.3     283.945
1          NaN          6.2     124.000
2         49.0          5.7      97.785
3          NaN          5.8       7.434
4         35.0          4.9      33.444
..         ...          ...         ...
987        NaN          5.1       3.750
988        NaN          6.4       6.378
989        NaN          5.9       3.318
990        NaN          5.5       2.339
991       78.0          8.0     410.437

[992 rows x 19 columns]

In [18]:
df.dtypes

imdb_id         object
title           object
plot            object
type            object
rated           object
year            object
released_at     object
added_at        object
runtime         object
genre           object
director        object
writer          object
actors          object
language        object
country         object
awards          object
metascore      float64
imdb_rating    float64
imdb_votes     float64
dtype: object

Features to use:
- genre : dummy
- imdb_rating 
- imdb_votes
- year

In [11]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()

In [80]:
df4= df[['genre','imdb_rating', 'imdb_votes', 'year']]

In [91]:
dfnum= df[['imdb_rating', 'imdb_votes']]

In [95]:
scaled_df = scaler.fit_transform(dfnum)
scaled_df = pd.DataFrame(scaled_df, columns=['imdb_rating', 'imdb_votes'])
X1= scaled_df
y1= 
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.3, random_state=42)

In [94]:
dummy= pd.get_dummies(df['type'])
dummy

     episode  movie  series
0          0      1       0
1          0      0       1
2          0      1       0
3          0      1       0
4          0      1       0
..       ...    ...     ...
987        0      1       0
988        0      1       0
989        0      1       0
990        0      1       0
991        0      1       0

[992 rows x 3 columns]

In [96]:
df4= df[['genre','imdb_rating', 'imdb_votes', 'year']]
df1 = df['genre'].str.split(', ', expand=True)

# Creamos variables dummy para cada género
dummy_vars = pd.get_dummies(df1, prefix='genre', prefix_sep='_')

# Combinamos el dataframe original con las variables dummy
df2 = pd.concat([df, dummy_vars], axis=1)

# Mostramos el resultado
print(dummy_vars)
features= [
'imdb_rating','year']
df3= df[features]
X = pd.concat([df3, dummy_vars], axis=1, join='inner')

     genre_Action  genre_Adventure  genre_Animation  genre_Biography  \
0               0                0                0                0
1               0                0                1                0
2               0                1                0                0
3               0                0                1                0
4               0                1                0                0
..            ...              ...              ...              ...
987             0                0                0                0
988             0                1                0                0
989             0                0                0                0
990             0                1                0                0
991             0                0                1                0

     genre_Comedy  genre_Documentary  genre_Drama  genre_Family  \
0               1                  0            0             0
1               0                  0            0             0
2               0                  0            0             0
3               0                  0            0             0
4               0                  0            0             0
..            ...                ...          ...           ...
987             1                  0            0             0
988             0                  0            0             0
989             1                  0            0             0
990             0                  0            0             0
991             0                  0            0             0

     genre_History  genre_Music  ...  genre_Sport  genre_Thriller  \
0                0            0  ...            0               0
1                0            0  ...            0               0
2                0            0  ...            0               0
3                0            0  ...            0               0
4                0            0  ...            0               0
..             ...          ...  ...          ...             ...
987              0            0  ...            0               0
988              0            0  ...            0               0
989              0            0  ...            0               0
990              0            0  ...            0               0
991              0            0  ...            0               0

     genre_Fantasy  genre_Mystery  genre_Sci-Fi  genre_Western  genre_Mystery  \
0                0              0             0              0              0
1                0              0             0              0              0
2                0              0             0              0              0
3                0              0             0              0              0
4                0              0             0              0              0
..             ...            ...           ...            ...            ...
987              0              0             0              0              0
988              0              0             0              0              0
989              0              0             0              0              0
990              0              0             0              0              0
991              0              0             0              0              0

     genre_Thriller  genre_Romance  genre_Thriller
0                 0              0               0
1                 0              0               0
2                 0              0               0
3                 0              0               0
4                 0              0               0
..              ...            ...             ...
987               0              0               0
988               0              0               0
989               0              0               0
990               0              0               0
991               0              0               0

[992 rows x 121 columns]

In [97]:
from sklearn.model_selection import train_test_split
y=df['imdb_votes']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#### - Does my data set have any categorical data, such as Gender or day of the week?

Yes,it does have categorical data, I'll use the genre of the movies and also the year that is sometimes a range of the year where the movie/Serie was relased
- Do my features have data values that range from 0 - 100 or 0-1 or both and more?
I also do have numeric values like the 'imdb_votes' and the 'imdb_rating'.